### ISSUE TITLE
usage with wizard scenes

### ISSUE THREAD

**Issue by ArnurArykbaev** [mcpeblocker/telegraf-pagination#8]
![image](https://user-images.githubusercontent.com/94394308/202129173-2b577097-4ece-4f63-8e00-152b43b0682a.png)
Please tell me how to use the stage. If I use return await ctx.wizard.next() , then the next scene starts with the ${callback-data}-next callback. If you remove ctx.wizard.next() at all, then the next scene simply does not start
  
```
const { Telegraf, Composer, Scenes, session, Markup } = require("telegraf");
const bot = new Telegraf(process.env.BOT_TOKEN);
const { Pagination } =  require('telegraf-pagination');



const startWizard = new Composer();
startWizard.on("text", async (ctx) => {
  const trackerMessage = `some text`;
  await ctx.reply(trackerMessage);
  return ctx.wizard.next();
});

const searchTorrent = new Composer();
searchTorrent.on("text", async (ctx) => {
   arrayRes = [
{title: 'fist', id: 1},
{title: 'second', id: 2}, 
{title: 'third', id: 3}, 
{title: 'fourth', id: 4}, 
{title: 'fifth', id: 5}, 
{title: 'sixth', id: 6}, 
{title: 'seventh', id: 7}, 
{title: 'eighth', id: 8},
{title: 'ninth', id: 9}, 
{title: 'tenth', id: 10}, 
{title: 'eleventh', id: 11}, 
{title: 'twelfth', id: 12}, 
{title: 'thirteenth', id: 13}
]
    const pagination = new Pagination({
      data: arrayRes, 
      //some options
    });

    pagination.handleActions(searchTorrent);
  
    let text = await pagination.text(); 
    let keyboard = await pagination.keyboard(); 
    await ctx.replyWithHTML(text, keyboard);
    
    return await ctx.wizard.next()
  }

});

const searchTorrentAction = new Composer();
searchTorrentAction.action(/.+/, async (ctx) => {
  await ctx.deleteMessage();
  console.log(ctx, 'CONTEXT');
  return ctx.scene.leave();
});


/* Scenes declare */
const menuScene = new Scenes.WizardScene(
  "sceneWizard",
  searchTorrent,
  searchTorrentAction,
);
const stage = new Scenes.Stage([menuScene]);

/* middleware to scenes */
bot.use(session());
bot.use(stage.middleware());

bot.on("text", (ctx) => ctx.scene.enter("sceneWizard"));
```

**Comment by mcpeblocker** [comment]
Hi there!

I assume that you are giving Composer instance for `pagination.handleActions()` function. So the handler middlewares of pagination are registered for that Composer instance. I suggest you use to use WizardScene instance instead of Composer instance as a parameter for `pagination.handleActions()` function.
Also note that you don't need to handle callback_data manually. You can just use onSelect option, there you will have item, index and ctx (Context instance, that was not mentioned in Readme, my bad...).

Thank you for reaching me out for that particular problem.

**Comment by ArnurArykbaev** [comment]
I used pagination.handleActions(menuScene) instead pagination.handleActions(searchTorrent) on your advice and it worked. Thank you!
